title: "プログラミングの基礎概念"
summary: |-
  ・集合
  　・数学知識は必要か
  　・一般概念の場合
  　・ベン図
  　・知識表現
  　・is-aとhas-a
  　・素性構造
  ・論理
  　・集合との関係
  　・命題
  　・推論
  ・プログラミング
  　・入出力とデータ加工
  　・純粋関数
  　・型システム
topics: []
published: false
price: 0
toc_depth: 2
chapters:
  - "88016b"
  - "63ba04"
allow_override: true